"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MagicWand.py']
APP_NAME = "MagicWand"
DATA_FILES = ["placeholder.png"]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'MagicWand.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Mouse control through air gestures",
        'CFBundleIdentifier': "com.lambda-shuttle.magicwand",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2022, Table 30, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
